language: node_js
node_js:
- '0.10'

before_install:
- npm install -g npm

install:
- npm install
- cd ./example && npm install && cd -

script:
- node ./node_modules/mocha/bin/mocha
- cd example && node ./build.js && cd -

deploy:
  provider: npm
  email: aymeric@beaumet.me
  api_key:
    secure: DF3qBU5Wn+hqrP5ssNSkoMPcYHxEPDrb03TC2GCI5TpYpHsVYcTFWA7sQ0ENsfQbTSz1LdCUV3UMycGIbqp8hOal9ysZ7gh0pO/K8NjGPS7R2mdPKfQTVonnOl/wHHSdbCLbyKFqmVDivjC5sCDy4Ucn1tuCNLkFOY02zkGVcAM=
  on:
    repo: aymericbeaumet/metalsmith-define
    branch: master
    tags: true
