language: node_js
node_js:
  - 4
  - 5

install:
  - npm install
  - pushd example && npm install && popd

script:
  - node --version && npm --version
  - npm test
  - pushd example && node build.js && popd

after_success:
  - npm run codeclimate

###

addons:
  code_climate:
    repo_token:
      secure: dTztDhP50vNPNk1WDQGl41olUvTM+lJ9AW+cJx1tgI+wn1+vjfmJhT3zUvGu1cUNKpYpCk0ioaIWbvjsMQa3tdz2wtM5yFjV9v5A/HgwmCP/wnYtsQZcMFNYvcIgSjbFOUSGohmYPa3VastK0TtqOvYkxqtEYuzrUM4saMte7iI=

git:
  depth: 10

matrix:
  fast_finish: true

sudo: false
