language: node_js
node_js:
  - "0.10"

before_install:
  - npm install -g npm

install:
  - npm install
  - cd ./example && npm install && cd -

script:
  - node ./node_modules/mocha/bin/mocha
  - cd example && node ./build.js
